### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#149] opened 2020-11-05 11:28 UTC
Now that the bridge has been rebuild we will need to see how to set up a server to have Gama running in a headless mode.

I am not sure what is the best way to do it, I guess to having it running on cityIO server, maybe it would make sense to ask nexus for a dedicated GAMA server, but not sure how to do it.

@crisjf if you want to have a look at the headless here is the doc
https://gama-platform.github.io/wiki/Headless

Maybe it would make sense to have a meta script in python that can handle the triggering of GAMA.

**Comment by RELNO** [comment] 2020-11-05 13:41
@agrignard getting a dedicated VM from necsys is quite simple, send a request to help@media.mit.edu . Running it on the same server as cityIO might have negative effects since both apps might fight on the same resources. Actually @doorleyr is now migrating his module to a dedicate VM for the same reason.

**Comment by crisjf** [comment] 2020-11-05 15:48
They even have a docker image!

https://hub.docker.com/r/gamaplatform/gama

**Comment by crisjf** [comment] 2020-11-06 17:10
Totally headless, running inside a docker container, and entering idle mode as soon as the update is done. We are making incredible progress on this thing!

![image](https://user-images.githubusercontent.com/8973959/98394570-f5d3a100-2028-11eb-9b8d-525267ea0563.png)

**Comment by crisjf** [comment] 2020-11-06 17:19
The documentation still needs some love, but the three main commands are here:

https://github.com/CityScope/CS_Simulation_GAMA/tree/master/CS_CityScope_GAMA/models/cityIO

@agrignard or @RELNO can you request a VM for GAMABrix?

**Comment by agrignard** [comment] 2020-11-06 17:35
Wha @crisjf ! Congrats! you're on fire!

**Comment by crisjf** [comment] 2020-11-06 18:24
@doorleyr will give @agrignard and me access to the CS_Modules vm

**Comment by agrignard** [comment] 2020-11-09 09:09
FYI 
https://github.com/gama-platform/gama.docker/issues/4

**Comment by crisjf** [comment] 2020-11-09 22:25
I'm gonna close this for now, as the issue is solved and the only remaining thing is to deploy it in a VM for continuous testing.

**Comment by crisjf** [comment] 2020-11-12 15:14
I created a separate script for the current version of the random walker model and linked it to `dungeonmodule` table 
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=dungeonmodule

I'll leave this running continuously in `csmodules.media` so we can test frequently.

**Closed by crisjf** 2020-11-12 15:14 UTC
Labels: cityIO
